### PR TITLE
Initial Bazel (obazl) support commit

### PR DESCRIPTION
**Pull request by mobileink**
Signed-off-by: Gregg Reynolds <601396+mobileink@users.noreply.github.com>

### CODE REVIEW

**Comment by mobileink** [comment]
minor fix, update to latest obazl

**Comment by psteckler** [comment]
@mobileink Can you create a PR comment explaining how we can try this code? I'm not familiar with Bazel.

**Comment by mobileink** [comment]
@psteckler Sure, detailed docs on the way. Later today or early tomorrow.

**Comment by psteckler** [comment]
> Sure, detailed docs on the way

Great, thanks!

**Review by bkase — APPROVED** [review]
Detailed docs are PR-ed in the main Coda repo so I think we should be good now!

**Pull request merged**
